version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    container_name: web
    ports:
      - '3000:3000'
    networks:
      - node-network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:8080'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - node-network
  db:
    image: mysql
    command: --innodb-use-native-aio=0 && --lower_case_table_names=2
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init/init-sql.sql:/docker-entrypoint-initdb.d/init-sql.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
      - MYSQL_BIND_ADDRESS=0.0.0.0
      - MYSQL_BIND_INTERFACE=0.0.0.0
    ports:
      - "3306:3306"
    expose:
      - '3306'
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

